version: "3.8"

name: beatdrop

services:
  db:
    image: postgres:latest
    container_name: beatdrop-db
    restart: unless-stopped
    ports:
      - "5454:5432"
    environment:
      POSTGRES_DB: beatdrop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
volumes:
  postgres_data:
    driver: local
