// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type Beat struct {
	ID          uuid.UUID  `json:"ID"`
	User        *User      `json:"user"`
	Location    string     `json:"location"`
	Timestamp   int32      `json:"timestamp"`
	Song        string     `json:"song"`
	Artist      string     `json:"artist"`
	Description string     `json:"description"`
	Comments    []*Comment `json:"comments"`
	Longitude   float64    `json:"longitude"`
	Latitude    float64    `json:"latitude"`
}

type Comment struct {
	ID        uuid.UUID `json:"id"`
	Timestamp int32     `json:"timestamp"`
	User      *User     `json:"user"`
	Comment   string    `json:"comment"`
}

type Mutation struct {
}

type NewBeat struct {
	User        string  `json:"user"`
	Location    string  `json:"location"`
	Song        string  `json:"song"`
	Artist      string  `json:"artist"`
	Description string  `json:"description"`
	Longitude   float64 `json:"longitude"`
	Latitude    float64 `json:"latitude"`
}

type NewComment struct {
	User    string `json:"user"`
	Comment string `json:"comment"`
}

type NewUser struct {
	Name     string `json:"name"`
	Username string `json:"username"`
	Bio      string `json:"bio"`
}

type Query struct {
}

type User struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Username string    `json:"username"`
	Bio      string    `json:"bio"`
}
