// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type AcceptFriend struct {
	ID uuid.UUID `json:"id"`
}

type Beat struct {
	ID          uuid.UUID `json:"id"`
	User        *User     `json:"user"`
	Location    string    `json:"location"`
	Timestamp   int32     `json:"timestamp"`
	Song        string    `json:"song"`
	Artist      string    `json:"artist"`
	Description string    `json:"description"`
	Longitude   float64   `json:"longitude"`
	Latitude    float64   `json:"latitude"`
}

type Comment struct {
	ID        uuid.UUID `json:"id"`
	Timestamp int32     `json:"timestamp"`
	User      *User     `json:"user"`
	Beat      *Beat     `json:"beat"`
	Comment   string    `json:"comment"`
}

type DenyFriend struct {
	ID uuid.UUID `json:"id"`
}

type Friend struct {
	ID        uuid.UUID `json:"id"`
	Alpha     *User     `json:"alpha"`
	Beta      *User     `json:"beta"`
	Timestamp int32     `json:"timestamp"`
	Status    int32     `json:"status"`
}

type Mutation struct {
}

type NewBeat struct {
	User        uuid.UUID `json:"user"`
	Location    string    `json:"location"`
	Song        string    `json:"song"`
	Artist      string    `json:"artist"`
	Description string    `json:"description"`
	Longitude   float64   `json:"longitude"`
	Latitude    float64   `json:"latitude"`
}

type NewComment struct {
	User    uuid.UUID `json:"user"`
	Beat    uuid.UUID `json:"beat"`
	Comment string    `json:"comment"`
}

type NewFriend struct {
	User   uuid.UUID `json:"user"`
	Friend uuid.UUID `json:"friend"`
}

type NewUser struct {
	Name     string `json:"name"`
	Username string `json:"username"`
	Bio      string `json:"bio"`
}

type Query struct {
}

type UpdateBio struct {
	User uuid.UUID `json:"user"`
	Bio  string    `json:"bio"`
}

type UpdateUsername struct {
	User     uuid.UUID `json:"user"`
	Username string    `json:"username"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Username  string    `json:"username"`
	Bio       string    `json:"bio"`
	Beatdrops int32     `json:"beatdrops"`
	Friends   int32     `json:"friends"`
	Settings  string    `json:"settings"`
	Photo     string    `json:"photo"`
}
